name: dc-mri

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8.*
  - pip
  - dcm2niix=1.0.20210317
  - git
  - git-annex
  - datalad=0.14.4
  - matplotlib
  - nibabel
  - nilearn=0.7.1
  - numpy
  - pandas

  - pip:
      - pybids
      - datalad-installer
